import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import "@react-pdf-viewer/core/lib/styles/index.css";
import "@react-pdf-viewer/default-layout/lib/styles/index.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Study Bot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Study with <span className="text-purple-300">GPT</span> App
        </h1>
        <h2 className="text-xl">
          Go to sample:{" "}
          <Link className="text-blue-600" href="/viewer">
            Sample
          </Link>
        </h2>
      </main>
    </>
  );
};

export default Home;
